name: Test Secret Configuration

on:
  push:
    branches:
      - main

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secret
        run: |
          echo "Testing HEROKU_API_KEY secret..."
          
          # Check if secret exists
          if [ -z "${{ secrets.HEROKU_API_KEY }}" ]; then
            echo "❌ HEROKU_API_KEY secret is NOT configured in GitHub!"
            echo "Please add it at: https://github.com/${{ github.repository }}/settings/secrets/actions"
            exit 1
          fi
          
          # Check secret length
          KEY_LENGTH=$(echo -n "${{ secrets.HEROKU_API_KEY }}" | wc -c)
          echo "Secret length: $KEY_LENGTH characters"
          
          if [ $KEY_LENGTH -lt 10 ]; then
            echo "❌ HEROKU_API_KEY seems too short!"
            exit 1
          fi
          
          echo "✅ HEROKU_API_KEY appears to be configured correctly"
          
      - name: Test with environment variable
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          if [ -z "$HEROKU_API_KEY" ]; then
            echo "❌ HEROKU_API_KEY not available as environment variable!"
            exit 1
          fi
          
          echo "✅ HEROKU_API_KEY is available as environment variable"
          echo "Length: ${#HEROKU_API_KEY}"