name: Test Minimal Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Starting minimal test..."
          echo "Repository: ${{ github.repository }}"
          echo "HEROKU_API_KEY exists: ${{ secrets.HEROKU_API_KEY != '' }}"
          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: List files
        run: |
          ls -la
          echo "---"
          echo "Checking key files:"
          test -f server.js && echo "✅ server.js exists" || echo "❌ server.js missing"
          test -f package.json && echo "✅ package.json exists" || echo "❌ package.json missing"
          test -f Procfile && echo "✅ Procfile exists" || echo "❌ Procfile missing"
          
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Install Heroku CLI
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          
          # Check API key
          if [ -z "$HEROKU_API_KEY" ]; then
            echo "❌ HEROKU_API_KEY is not set!"
            exit 1
          fi
          
          echo "✅ API key is set (length: ${#HEROKU_API_KEY})"
          
          # Test API key
          echo "Testing Heroku authentication..."
          heroku auth:whoami || exit 1
          
          # Create git repo if needed
          git init
          git add .
          git commit -m "Deploy from GitHub Actions" || echo "Nothing to commit"
          
          # Add remote
          git remote add heroku https://git.heroku.com/locumtruerate-staging.git || true
          
          # Push
          echo "Pushing to Heroku..."
          git push heroku main:main --force